# Generated by Django 4.1.6 on 2023-02-12 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 8, 17, 9, 123171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 8, 17, 9, 124541, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='storeowner',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 12, 8, 17, 9, 123392, tzinfo=datetime.timezone.utc)),
        ),
    ]
